var szovegek = [
    "Sergio Leone háromórás mesterműve, amely megváltoztatta a western műfaját, és ma már a filmművészet legnagyobb klasszikusai között tartják számon. A film három fő karakterének története bonyolult és mélyen emberi, miközben egy elásott kincs felkutatásának izgalmas nyomozásába keverednek az amerikai polgárháború hátterében. Clint Eastwood ikonikus szerepe, mint Blondie, egyedülálló karizmával és hűvös távolságtartással tölti meg a vásznat, míg Eli Wallach Tuco szerepe rendkívül színes és sokszor komikus, mégis tragikus karaktert alkot. Lee Van Cleef mint Angel Eyes, a hűtlen, hideg vérű gyilkos, igazán emlékezetes, miközben a film folyamatosan dolgozik a jó és a rossz közötti morális határok lebontásával. A zene, amely Ennio Morricone munkája, a film egyik legfontosabb és legikonikusabb elemévé vált, és minden egyes dallam hangja ma már egyenértékű a western műfajával. Az utolsó párbaj jelenet talán a filmtörténet egyik legfeszültebb és legemlékezetesebb pillanata, ahol minden mozdulat és szemvillanás sorsdöntő lehet. Az \"A Jó, a Rossz és a Csúf\" nem csupán egy akciófilm; filozófiai és etikai kérdéseket feszeget, mint például: Mi teszi az embert jóvá vagy rosszá? Hogyan küzdhetünk egy igazságos világ megteremtéséért egy annyira romlott világban? A film egyfajta szimbolikus tanulmány a túlélésről és az önállóságról, miközben bemutatja a világ egyik legellentmondásosabb hőstípusát: az antiszociális magányos harcost.",
    
    "Jason Statham egy újabb kemikátornak öltöztetett karaktere ebben a gyors tempójú, izgalmas akciódrámában. Levon Cade, a visszavonult terrorelhárító, aki valaha egy kemikusan precíziós bűnüldözési rendszer része volt, most egy utolsó, személyes küldetésre indul. A film egy különleges felfedezőútnak tűnik a bűn világába, amely az igazság keresésére és a maffia elleni harcra összpontosít. A feszültséggel teli film során Cade összefonódik a múltjával, miközben egy eltűnt tinédzsert keres, akit a maffia fogságában tart. A film legnagyobb erőssége az, hogy a cselekmény folyamatosan rétegezi az érzelmi és akciódús jeleneteket, miközben a karakterek emberi oldalát is bemutatja. Mindez a különböző karakterek és akciójelenetek közötti határokat szétfeszíti, ahogy egyre inkább kiderül, hogy a válaszok nem mindig olyan egyszerűek, mint amilyenek a kérdések. A főszereplő belső küzdelme és az őt körülvevő világ drámai kontrasztja, amelyben minden választásnak következménye van, mindvégig érzékelteti az erkölcsi dilemmák jelentőségét. Jason Statham kiválóan alakítja a magányos, mélyen traumatizált férfit, aki minden egyes lépésével próbálja megtalálni a saját helyét a világban.",
    
    "Ez a dokumentumfilm három nap történetét meséli el Auschwitz borzalmas falai között, bemutatva a tábor valóságát egy olyan szemszögből, amely ritkán kap figyelmet. A rendező a saját családjának történetét is belefonja a filmbe, így a túlélők visszaemlékezései nem csupán egy történelmi eseményt, hanem személyes drámákat is bemutatnak. A film egyetlen pillanatra sem engedi el a nézőt; az erőszakos történelem és az emberi elme viszontagságai szembesítik a közönséget a holokauszt szörnyűségeivel. A dokumentumfilm több szinten is emléket állít a történelem legtragikusabb eseményeinek, miközben a túlélők szembesítéseivel próbálja felhívni a figyelmet arra, hogy az emberi méltóság megőrzésére tett kísérletek a legnagyobb nehézségek ellenére is lehetségesek. A filmben az interjúk, a történetek és az archív felvételek keverednek, hogy a nézők valóban átérezhessék a katasztrófa emberi oldalát, miközben a film arra is figyelmeztet, hogy a múlt tanulságai hogyan formálhatják a jövőt.",
    
    "Egy izgalmas thriller, amely az igazság keresése során merészkedik a háború utáni világ sötét rétegeibe. A főszereplő egy fiatal nő, aki a náci háborús bűnösök után nyomoz, hogy megállítsa őket és végrehajtsa a saját formájú igazságszolgáltatást. Az őt körülvevő világ, amely tele van családokkal és emberekkel, akik képtelenek megbocsátani a háború szörnyűségeit, mély filozófiai kérdéseket vet fel a bosszú és a megbocsátás mibenlétéről. A film emellett azokat a lelki és morális dilemmákat is feszegeti, amelyekkel egy háború utáni társadalomnak szembe kell néznie, hogy helyreállítsa az igazságot és helyet adjon a gyógyulásnak. A történet folyamatosan a feszültség és a karakterek közötti pszichológiai harcok építésére épít, miközben a hősies küzdelem során a főszereplő nemcsak az igazságra, hanem saját szellemi és érzelmi gyógyulására is rátalál.",
    
    "A \"Jurassic Park\" nemcsak a látványvilág, hanem a tudomány és etika határvonalainak feszegetésével is korszakalkotó volt. Spielberg egy olyan világot teremtett, amely egyszerre csábítja és rémíti meg a nézőt: egy titokzatos sziget, ahol a tudomány határvonalát átlépve, a dinoszauruszokat újra életre keltik. A filmben a látvány mellett a tudományos kérdések és filozófiai gondolatok is kulcsszerepet kapnak, mint például: Mi történik, ha az emberi kíváncsiság túllép a természet korlátain? Hogyan kezelhetjük a tudományt, amelynek hatásai messze túlmutatnak a saját érdekünkön? A film legfontosabb üzenete, hogy bár a tudomány sok csodálatos dolgot hozhat létre, bizonyos dolgokat nem szabad a saját érdekünkben manipulálni. Az emberi kapzsiság és az erkölcsi felelősség kérdései központi szerepet kapnak, miközben a látványos dinoszauruszokkal teli akciójelenetekkel szórakoztatja a közönséget. Az izgalmas, gyors tempójú cselekmény és a meglepő fordulatok mind a nézők izgatott figyelmét szolgálják.",
    
    "Ez a horrorfilm izgalmas betekintést nyújt a digitális világ sötétebb oldalába, ahol a közönség és az influenszerek kapcsolatának titkai egyre inkább kontrollálhatatlanná válnak. A fiatal influenszer, aki egy szórakoztató élő közvetítést indít, hamarosan olyan erőket szabadít el, amelyek túlmutatnak minden elképzelésén. A film rendkívül ügyesen használja a digitális kultúra aktuális trendjeit, hogy rámutasson, milyen veszélyekkel járhat a túlzott nyilvánosságra hozott élet. Az események lassan egy sötét fordulathoz érkeznek, amely nemcsak a főszereplőt, hanem minden egyes nézőt magával ragad. Ahogy a határok a digitális és a fizikai világ között egyre inkább elmosódnak, úgy válik a film egy társadalmi kommentárrá, amely figyelmeztet az influenszerek és a követőik közötti hatalmas szakadékról és a valóság manipulálásáról.",
    
    "A Minecraft világában játszódó film az egyik legújabb próbálkozás, hogy a videojátékokat a vászonra vigyék, és minden, amit a játék képvisel, életre keljen. A filmben egy fiatal, bátor játékos és barátai egy epikus küldetésre indulnak, hogy legyőzzék az Ender Sárkányt, miközben a Minecraft híres építési és túlélési aspektusait is bemutatják. Az egész történet humoros és kalandos, miközben értékes tanulságokat hoz a csapatmunkáról, a barátságról és a kreativitás fontosságáról. A film lehetőséget ad arra, hogy a fiatal nézők elmerüljenek abban a világban, amelyet annyira szeretnek, miközben a felnőttek is megtalálhatják benne a szórakoztató és könnyed üzeneteket. A cselekmény, amely a Minecraft világának izgalmait és veszélyeit ötvözi, igazi családi élménnyé válik. Emellett a film az építkezés, a túlélés és a problémamegoldás fontosságát is hangsúlyozza.",
    
    "Francis Ford Coppola mesterműve, a \"Keresztapa\" az egyik legnagyobb hatású film, amely valaha készült. A történet középpontjában egy olasz-amerikai maffiacsalád, a Corleonék áll, akiknek fejét, Don Vito Corleone-t (Marlon Brando) játsza a legendás színész. A film a család belső dinamikáját és hatalmi harcait mutatja be, miközben betekintést nyújt a maffia világának törvényeibe és erkölcsi dilemmáiba. Al Pacino játssza Michael Corleone-t, Vito legfiatalabb fiát, aki először próbálja távol tartani magát a család ügyeitől, de a film során fokozatosan belesodródik a család ügyeibe, és végül maga is egy véres maffiafőnökké válik. A film egy epikus történet a hatalom, a család, a hűség és a bűnözés komplex viszonyáról, amely mély filozófiai kérdéseket vet fel: Mi a család szerepe egy férfi életében? Hogyan egyesíthető a személyes élet és a bűnözés? A \"Keresztapa\" nem csupán egy akciófilm, hanem egy komoly társadalmi és pszichológiai tanulmány is, amely az amerikai társadalom egyik legnagyobb vívódásait, a bűnözést és annak hatásait tárja elénk. A film zenei kísérete, Nino Rota ikonikus dallama, az egyik legelérhetőbb és legemlékezetesebb filmzeneként vonult be a történelembe. A \"Keresztapa\" nemcsak egy klasszikus film, hanem egy alapmű, amely megváltoztatta a filmtörténetet és amely azóta is mércét jelent minden hasonló típusú film számára."

]

var imgk = ["./film_img/gbu.jfif", "./film_img/awm.jfif", "./film_img/au.jfif", "./film_img/hh.jfif", "./film_img/js.jfif", "./film_img/ls.jfif", "./film_img/minecraft.jfif", "./film_img/thegodfather.jfif"]
var cim = ["A Jó, a Rossz és a Csúf", "A melós", "Three Days In Auschwitz", "The Huntress of Auschwitz", "Jurassic Park", "Livestream", "Egy Minecraft film","A Keresztapa"]
function oszlopbetoltes() {
    for(var i=0; i<8; i++){
        var egy = Math.floor(Math.random() * (10 - 8 + 1)) + 8;
        var ketto = Math.floor(Math.random() * (10 - 7 + 1)) + 7;
        sor.push(egy)
        oszlop.push(ketto)
    }
}

var sor = []
var oszlop = []
var pirosak = [[],[],[],[],[],[],[],[]]
var zoldek = []